// Banque des 100 cartes désignées de Greed Island (docs/CARTES_GREED_ISLAND.md, décisions du 2026-10-10) :
// numéro de l'anime (RG-8.1 amendé), nom français, rang de notre jeu selon la rareté, texte d'ambiance
// réécrit en description (les cartes désignées n'ont aucun effet). Le GM compose son catalogue en y piochant.
import type { Rank } from './domain.js';

export interface CarteBanque {
  numero: number;
  nom: string;
  rang: Rank;
  texte: string;
}

export const BANQUE_CARTES: readonly CarteBanque[] = [
  { numero: 0, nom: "Le bonheur du détenteur", rang: 'SS', texte: "Un château et sa ville de 10 000 habitants, qui vivent selon les lois de son détenteur." },
  { numero: 1, nom: "Le bois secret d'un Tsubo", rang: 'S', texte: "L'entrée du Jardin du Dieu de la Montagne, peuplé d'espèces uniques et dociles." },
  { numero: 2, nom: "La côte d'un Tsubo", rang: 'S', texte: "L'entrée de la Caverne de Poséidon, dont le chemin change à chaque visite." },
  { numero: 3, nom: "Le vase de la fontaine", rang: 'B', texte: "Une jarre d'où coulent sans fin 1 440 litres d'eau pure par jour." },
  { numero: 4, nom: "La source naturelle des belles peaux", rang: 'B', texte: "Une source chaude qui guérit toute affection de la peau." },
  { numero: 5, nom: "La grotte des esprits", rang: 'S', texte: "Une grotte d'où l'on ressort dans un lieu désolé, à l'autre bout du pays." },
  { numero: 6, nom: "La fontaine de jouvence à alcool", rang: 'B', texte: "Une fontaine dont l'eau devient en une heure un alcool d'exception." },
  { numero: 7, nom: "La pierre de grossesse", rang: 'A', texte: "Deux pierres qui donnent un enfant à qui les porte un mois, même à un homme." },
  { numero: 8, nom: "Le lac du mystère", rang: 'A', texte: "Un étang où chaque poisson lâché devient deux le lendemain." },
  { numero: 9, nom: "L'arbre de la bonne récolte", rang: 'A', texte: "Un arbre chargé de tous les fruits du monde, plein à nouveau chaque matin." },
  { numero: 10, nom: "Le rurubu d'or", rang: 'B', texte: "Un guide doré qui dit où et quand rencontrer les personnes de son type." },
  { numero: 11, nom: "La balance d'or", rang: 'D', texte: "Une balance d'or qui, face à deux choix, penche toujours vers le meilleur." },
  { numero: 12, nom: "Le dictionnaire d'or", rang: 'A', texte: "Un dictionnaire dont un mot brille d'or chaque jour : il servira le lendemain." },
  { numero: 13, nom: "Le carnet du bonheur", rang: 'B', texte: "Un carnet où s'épargnent les petites chances du quotidien, changées en argent." },
  { numero: 14, nom: "Les ciseaux coupe-liens", rang: 'C', texte: "Des ciseaux qui coupent à jamais le lien avec la personne d'une photo découpée." },
  { numero: 15, nom: "Le génie capricieux", rang: 'A', texte: "Un génie qui exauce trois vœux, choisis parmi mille propositions toutes différentes." },
  { numero: 16, nom: "L'avertissement du maître des fées", rang: 'S', texte: "Un roi des fées qui donne de justes conseils sur ce qui manque, quand il le décide." },
  { numero: 17, nom: "Le souffle du grand ange", rang: 'S', texte: "Le souffle d'un ange, qui guérit toutes les blessures et toutes les maladies. Une seule fois." },
  { numero: 18, nom: "Le petit clin d'œil du démon", rang: 'B', texte: "Un petit démon dont chaque clin d'œil procure une extase incomparable. On s'y accoutume vite." },
  { numero: 19, nom: "L'oreiller de l'esprit joueur", rang: 'B', texte: "Un oreiller qui laisse l'esprit vagabonder pendant le sommeil, 24 heures au plus." },
  { numero: 20, nom: "Le mètre de pulsions spirituelles", rang: 'D', texte: "Une horloge qui règle l'état d'esprit comme on règle l'heure." },
  { numero: 21, nom: "Les lunettes squelettes", rang: 'C', texte: "Des lunettes qui voient à travers tout, sauf un paquet de sorts de Masadora." },
  { numero: 22, nom: "Toraemon", rang: 'C', texte: "Une bête rare qui fourre des trésors dans sa poche à quatre dimensions." },
  { numero: 23, nom: "Le livre infini", rang: 'D', texte: "Un livre qui raconte une histoire différente à chaque ouverture." },
  { numero: 24, nom: "La télé probable", rang: 'B', texte: "Une télévision qui montre trente heures de ce qui se passerait si…" },
  { numero: 25, nom: "Le dé du risque", rang: 'D', texte: "Un dé de dix-neuf étoiles et une tête de mort. La tête de mort efface tout." },
  { numero: 26, nom: "Les sept nains au travail", rang: 'C', texte: "Sept nains qui abattent tout le travail pendant le sommeil de leur maître." },
  { numero: 27, nom: "Le carnet de ticket de bus-visage", rang: 'C', texte: "Un carnet de mille passes qui ouvrent toutes les portes." },
  { numero: 28, nom: "La télécommande à sentiments", rang: 'C', texte: "Une télécommande qui règle ce qu'une personne ressent pour une autre." },
  { numero: 29, nom: "Coupon de réservation forcée", rang: 'C', texte: "Un coupon qui obtient n'importe quel produit, si rare soit-il." },
  { numero: 30, nom: "Coussin connexion", rang: 'C', texte: "Un coussin : qui s'y assied rend un service à son propriétaire." },
  { numero: 31, nom: "Carte postale aller-retour pour les morts", rang: 'B', texte: "Une carte postale pour écrire à un défunt, qui répond le lendemain." },
  { numero: 32, nom: "Le bonbon mainate", rang: 'D', texte: "Un bonbon qui donne la voix de son choix." },
  { numero: 33, nom: "Cookie aux hormones", rang: 'B', texte: "Un biscuit qui change de sexe pendant 24 heures." },
  { numero: 34, nom: "Enquête sur tout", rang: 'D', texte: "Un questionnaire auquel on répond toujours avec franchise." },
  { numero: 35, nom: "Kit caméléon", rang: 'S', texte: "Un kit qui change en n'importe quel animal, sans changer de masse." },
  { numero: 36, nom: "La salle de recyclage", rang: 'A', texte: "Une salle où ce qui est cassé ressort neuf 24 heures plus tard." },
  { numero: 37, nom: "L'œuf du sportif de niveau extra-super", rang: 'D', texte: "Un œuf qui, couvé des années, fait de son gardien un grand athlète." },
  { numero: 38, nom: "L'œuf de l'artiste de niveau extra-super", rang: 'D', texte: "Un œuf qui, couvé des années, fait de son gardien un grand artiste." },
  { numero: 39, nom: "L'œuf du politicien de niveau extra-super", rang: 'D', texte: "Un œuf qui, couvé des années, fait de son gardien un grand politicien." },
  { numero: 40, nom: "L'œuf du musicien de niveau extra-super", rang: 'D', texte: "Un œuf qui, couvé des années, fait de son gardien un grand musicien." },
  { numero: 41, nom: "L'œuf du pilote de niveau extra-super", rang: 'D', texte: "Un œuf qui, couvé des années, fait de son gardien un grand pilote." },
  { numero: 42, nom: "L'œuf du romancier de niveau extra-super", rang: 'D', texte: "Un œuf qui, couvé des années, fait de son gardien un grand romancier." },
  { numero: 43, nom: "L'œuf du grand gambler", rang: 'D', texte: "Un œuf qui, couvé des années, fait de son gardien un grand joueur." },
  { numero: 44, nom: "L'œuf du grand acteur", rang: 'D', texte: "Un œuf qui, couvé des années, fait de son gardien un grand acteur." },
  { numero: 45, nom: "L'œuf du grand patron", rang: 'D', texte: "Un œuf qui, couvé des années, fait de son gardien un grand patron." },
  { numero: 46, nom: "La jeune fille à la poudre d'or", rang: 'B', texte: "Une jeune fille dont le bain quotidien laisse 500 g de poudre d'or. Très timide." },
  { numero: 47, nom: "La jeune fille endormie", rang: 'A', texte: "Une jeune fille qui dort à la place de son maître, éveillé jour et nuit." },
  { numero: 48, nom: "La jeune fille parfumée", rang: 'B', texte: "Une jeune fille dont le parfum chasse tout le stress." },
  { numero: 49, nom: "La sirène qui s'emballe", rang: 'C', texte: "Une sirène qui tient dans la main et chante quand elle est heureuse." },
  { numero: 50, nom: "Le zaurus qui s'emballe", rang: 'A', texte: "Un petit saurien dont chaque génération donne une nouvelle espèce." },
  { numero: 51, nom: "Le dragon qui s'emballe", rang: 'A', texte: "Un petit dragon qui obéit à son maître et finit par parler, s'il est élevé avec amour." },
  { numero: 52, nom: "La perle de sauterelle", rang: 'D', texte: "Des criquets qui cachent chacun une perle." },
  { numero: 53, nom: "King white ookuwagata", rang: 'D', texte: "Un scarabée blanc qui bâtit une immense colonie d'insectes." },
  { numero: 54, nom: "Le papillon millénaire", rang: 'C', texte: "Un papillon : qui le capture fait prospérer sa famille pour des générations." },
  { numero: 55, nom: "La boutique des contreparties", rang: 'C', texte: "Une boutique dont le gérant se venge à la mesure de la rancune de son client." },
  { numero: 56, nom: "La galerie de photos souvenirs", rang: 'C', texte: "Une galerie qui tire le portrait de son visiteur à n'importe quel moment de son passé." },
  { numero: 57, nom: "L'agent immobilier de maisons cachées", rang: 'A', texte: "Une agence qui loue une pièce secrète, connue de son seul locataire." },
  { numero: 58, nom: "Le vidéo club secret", rang: 'B', texte: "Un vidéo club qui loue les secrets des autres, sans jamais les montrer." },
  { numero: 59, nom: "L'école des langues étrangères instantanées", rang: 'C', texte: "Une école où des années d'étude se changent en quelques minutes de parfaite maîtrise." },
  { numero: 60, nom: "Le livreur d'objets perdus", rang: 'D', texte: "Un livreur qui rapporte le lendemain tout objet perdu qu'on lui décrit." },
  { numero: 61, nom: "Le chien en pièces", rang: 'C', texte: "Un chien qui fait un bilan de santé complet : « Rien à signaler » ou « Anomalie »." },
  { numero: 62, nom: "Le roi des clubs", rang: 'C', texte: "Un club où tout le monde obéit au roi ; une heure dedans vaut un jour dehors." },
  { numero: 63, nom: "Le restaurant virtuel", rang: 'D', texte: "Un restaurant où l'on commande de tout. La satiété n'y est qu'une illusion." },
  { numero: 64, nom: "L'élixir de la sorcière", rang: 'D', texte: "La pilule d'amour d'une sorcière : qui l'avale aime une semaine durant." },
  { numero: 65, nom: "L'élixir de jeunesse de la sorcière", rang: 'A', texte: "Les pilules de jeunesse d'une sorcière, un an de moins chacune. Gare à l'excès." },
  { numero: 66, nom: "L'amaigrissant de la sorcière", rang: 'C', texte: "Les pilules amincissantes d'une sorcière, un kilo de moins chacune." },
  { numero: 67, nom: "Le médicament de croissance", rang: 'D', texte: "Des pilules de croissance, un centimètre de plus chacune." },
  { numero: 68, nom: "Le médicament de renforcement mental", rang: 'C', texte: "Un remède qui décuple l'endurance et l'ardeur." },
  { numero: 69, nom: "Le médicament de repousse des cheveux du vieillard", rang: 'D', texte: "Une lotion qui fait pousser des cheveux partout où elle touche. À manier avec des gants." },
  { numero: 70, nom: "La pastille de renforcement musculaire du professeur fou", rang: 'B', texte: "Des pastilles qui donnent des muscles sans effort, au goût atroce." },
  { numero: 71, nom: "La pommade d'hormones du professeur fou", rang: 'C', texte: "Une pommade qui attire irrésistiblement… parfois un peu trop." },
  { numero: 72, nom: "La machine de remodelage du professeur fou", rang: 'B', texte: "Une machine qui remodèle le visage à volonté. Une fois sur vingt, elle échoue." },
  { numero: 73, nom: "Le jade des ténèbres", rang: 'B', texte: "Un jade béni par le Diable, qui détourne le malheur sur un autre." },
  { numero: 74, nom: "L'aigue-marine philosophale", rang: 'A', texte: "Une aigue-marine qui entoure son porteur d'amis brillants et fidèles toute sa vie." },
  { numero: 75, nom: "L'alexandrite de la chance", rang: 'C', texte: "Une alexandrite qui attire des expériences uniques, pour le meilleur ou pour le pire." },
  { numero: 76, nom: "Le rubis du destin", rang: 'D', texte: "Un rubis qui apporte une immense fortune, mais jamais plus d'une semaine au même endroit." },
  { numero: 77, nom: "L'émeraude qui attire la beauté", rang: 'A', texte: "Une émeraude qui fait accourir les experts de la beauté." },
  { numero: 78, nom: "Le saphir solitaire", rang: 'D', texte: "Un saphir qui apporte une immense fortune, et une vie entière de solitude." },
  { numero: 79, nom: "Le diamant arc-en-ciel", rang: 'C', texte: "Le diamant des demandes en mariage : la réponse est toujours oui." },
  { numero: 80, nom: "La pierre flottante", rang: 'S', texte: "Une pierre nourrie par le soleil, qui fait flotter une personne." },
  { numero: 81, nom: "Blue planet", rang: 'S', texte: "Un joyau bleu inconnu de la science, tombé de l'espace." },
  { numero: 82, nom: "La canne du châtiment céleste", rang: 'B', texte: "Une canne qui frappe le plus coupable des deux noms prononcés." },
  { numero: 83, nom: "L'épée de la vérité", rang: 'C', texte: "Une épée qui tranche en deux tout ce qui ment." },
  { numero: 84, nom: "Le collier du chevalier", rang: 'D', texte: "Un collier qui renvoie les malédictions et lève celles des cartes qu'il touche." },
  { numero: 85, nom: "L'armure de remplacement de corps", rang: 'A', texte: "Une armure contre laquelle toute arme issue d'une carte reste vaine." },
  { numero: 86, nom: "L'arc de l'échec", rang: 'A', texte: "Un arc dont chaque flèche vaut une « Évasion »." },
  { numero: 87, nom: "Le bouclier des prières", rang: 'B', texte: "Un bouclier qui bloque les sorts de déplacement à 20 mètres." },
  { numero: 88, nom: "Le grand marteau de l'immortalité", rang: 'B', texte: "Un marteau dont chaque coup frappe d'un sort d'attaque impossible à parer." },
  { numero: 89, nom: "La manchette de l'inspecteur du fisc", rang: 'C', texte: "La manchette d'un inspecteur du fisc, qui saisit au prix d'une carte de son porteur." },
  { numero: 90, nom: "Le casque de mémoire", rang: 'C', texte: "Un casque qui fait garder en mémoire tout ce qu'on voit et entend." },
  { numero: 91, nom: "Plaking", rang: 'C', texte: "Une maquette qui devient n'importe quel véhicule." },
  { numero: 92, nom: "Le ticket de kagemusha", rang: 'S', texte: "Un ticket pour vivre la vie de quelqu'un d'autre pendant 24 heures." },
  { numero: 93, nom: "L'encyclopédie de la vie", rang: 'D', texte: "Une encyclopédie de tous ceux qui ont croisé une vie, et de leurs conversations." },
  { numero: 94, nom: "L'épée du vol", rang: 'A', texte: "Une épée légendaire dont chaque coup vole une carte." },
  { numero: 95, nom: "Le manteau du secret", rang: 'C', texte: "Un manteau qui protège le Book de son porteur de tout regard indiscret." },
  { numero: 96, nom: "Le serpent aux yeux de mille miles", rang: 'B', texte: "Un serpent qui, nourri d'une carte, crache une « Sup'vision »." },
  { numero: 97, nom: "Caméra 3D", rang: 'C', texte: "Un appareil dont les photos se développent en objets en relief." },
  { numero: 98, nom: "Silver dog", rang: 'A', texte: "Un chien d'argent qui, nourri d'or, produit de l'argent massif." },
  { numero: 99, nom: "Maid panda", rang: 'S', texte: "Une servante panda, soigneuse, bonne cuisinière, parfaite avec les enfants." },
];

/** Carte de la banque par numéro de l'anime. */
export const carteDeBanque = (numero: number): CarteBanque | undefined => BANQUE_CARTES.find((c) => c.numero === numero);
